### ISSUE TITLE
Unexpected status code 500 when sending a new alert

### ISSUE THREAD

**Issue by alesnav** [nopp/alertmanager-webhook-telegram#2]
Hello there!

I'm facing a "little" problem when trying to use this Docker container. My main goal is to deploy noop/alertmanager-webhook-telegram inside [https://github.com/stefanprodan/swarmprom](swarmprom) stack.

Prometheus version 2.5.0
Alertmanager version 0.17.0

Alertmanager config file:
```
global:
  resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: telegram-webhook
receivers:
- name: telegram-webhook
  webhook_configs:
  - send_resolved: true
    http_config: {}
    url: http://alertmanager-telegram.DOMAIN/alert
templates: []
```

Alertmanager-telegram container definition:
```
  alertmanager-telegram:
    image: nopp/alertmanager-webhook-telegram
    networks:
      - monit
      - traefik_public
    environment:
      - "bottoken=xxTOKENxx"
      - "chatid=xxCHATIDxx"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - traefik.internal.frontend.rule=Host:alertmanager-telegram.DOMAIN
        - traefik.port=9119
        - traefik.docker.network=traefik_public
```

Error logs in Alertmanager container:
```
level=error ts=2019-06-30T16:53:28.29354978Z caller=notify.go:339 component=dispatcher msg="Error on notify" err="unexpected status code 500 from http://alertmanager-telegram.DOMAIN/alert"
level=error ts=2019-06-30T16:53:28.295665455Z caller=dispatch.go:264 component=dispatcher msg="Notify for alerts failed" num_alerts=4 err="unexpected status code 500 from http://alertmanager-telegram.DOMAIN/alert"
```

Do you have any idea to fix this issue? :worried:

Thanks!

**Comment by nopp** [comment]
Hi,
With this informations its impossible to know what happen, but you can add  debug=True on app.run(host='0.0.0.0', port=9119)

app.run(host='0.0.0.0', port=9119, debug=True)

After this, you can see more informations about the problem, and post here again!

**Comment by nopp** [comment]
I think I found the problem, do a new checkout and test again :)

**Comment by alesnav** [comment]
Hi @nopp , sorry, I'm using your Docker hub image and that has not been updated yet, so I cannot test it.

I should build a local registry in my environment, but it does not exist yet, sorry for that.

**Comment by nopp** [comment]
OK @alesnav I made a new one image on docker hub, try again :)

**Comment by alesnav** [comment]
Hi @nopp , sorry for the delay.
Now the HTTP error 500 is fixed :)
But I am facing the next one... It seems that `chatID` variable is not passed to the inner function. Please look at this error:

`bot.sendMessage(chat_id=chatID,text="Failed to send via Flask to Telegram!")`

<details><summary>Full trace</summary>
<p>

```

[2019-07-05 08:38:31,818] ERROR in app: Exception on /alert [POST]


Traceback (most recent call last):


  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2311, in wsgi_app


    response = self.full_dispatch_request()


  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1834, in full_dispatch_request


    rv = self.handle_user_exception(e)


  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1737, in handle_user_exception


    reraise(exc_type, exc_value, tb)


  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1832, in full_dispatch_request


    rv = self.dispatch_request()


  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1818, in dispatch_request


    return self.view_functions[rule.endpoint](**req.view_args)


  File "/alertmanager-webhook-telegram/flaskAlert.py", line 40, in postAlertmanager


    bot.sendMessage(chat_id=chatID,text="Failed to send via Flask to Telegram!")


  File "/usr/lib/python2.7/site-packages/telegram/bot.py", line 65, in decorator


    result = func(self, *args, **kwargs)


  File "/usr/lib/python2.7/site-packages/telegram/bot.py", line 90, in decorator


    result = self._request.post(url, data, timeout=kwargs.get('timeout'))


  File "/usr/lib/python2.7/site-packages/telegram/utils/request.py", line 309, in post


    headers={'Content-Type': 'application/json'})


  File "/usr/lib/python2.7/site-packages/telegram/utils/request.py", line 223, in _request_wrapper


    raise BadRequest(message)


dRequest: Chat not found

```

</p>
</details>

I am pretty sure that the `chatID` variable is set, because it is written in the script located at `/alertmanager-webhook-telegram/flaskAlert.py` and it is declared as environment vars in stack file:

```
    environment:
      - "bottoken=XXXXX"
      - "chatid=XXXXX"
```

**Comment by nopp** [comment]
I dont recognize this:
  environment:
      - "bottoken=XXXXX"
      - "chatid=XXXXX"

Look again your confs, I tested here, and all is ok, this is not an issue, closing.

**Comment by nopp** [comment]
I recommend you access the pod running the webhook, and see flaskAlert.py and verify if  bot token and chatId is correct.

**Comment by alesnav** [comment]
Ok, no problem. I'll dig into this issue to see the root cause of the problem, but maybe it is my misconfiguration instead of a bug in this case.

That lines are part of the stack definition. This is the full photo:

```
  alertmanager-telegram:
    image: nopp/alertmanager-webhook-telegram
    networks:
      - monit
      - traefik_public
    environment:
      - "bottoken=xxTOKENxx"
      - "chatid=xxCHATIDxx"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - traefik.internal.frontend.rule=Host:alertmanager-telegram.DOMAIN
        - traefik.port=9119
        - traefik.docker.network=traefik_public
```
